extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

// To keep guess times under 2 seconds, the first guess (after the hard-coded
// guess "serai") must be precomputed.
#[wasm_bindgen]
pub fn first_guess(
  hint1: usize,
  hint2: usize,
  hint3: usize,
  hint4: usize,
  hint5: usize,
) -> String {
  CACHE[hint1][hint2][hint3][hint4][hint5].to_owned()
}

const CACHE: [[[[[&'static str; 3]; 3]; 3]; 3]; 3] = [
  [
    [
      [
        [
          "phony",
          "linty",
          "mogul",
        ],
        [
          "nyala",
          "mania",
          "adapt",
        ],
        [
          "talon",
          "nidal",
          "hotel",
        ],
      ],
      [
        [
          "choon",
          "clint",
          "kombu",
        ],
        [
          "orant",
          "lakin",
          "guard",
        ],
        [
          "talon",
          "milty",
          "braai",
        ],
      ],
      [
        [
          "culty",
          "monty",
          "ultra",
        ],
        [
          "comby",
          "mania",
          "capri",
        ],
        [
          "alamo",
          "diram",
          "korai",
        ],
      ],
    ],
    [
      [
        [
          "dolce",
          "nitid",
          "flock",
        ],
        [
          "lawed",
          "maile",
          "naevi",
        ],
        [
          "pleon",
          "email",
          "about",
        ],
      ],
      [
        [
          "coted",
          "lined",
          "uteri",
        ],
        [
          "gator",
          "alarm",
          "uraei",
        ],
        [
          "arked",
          "rimae",
          "about",
        ],
      ],
      [
        [
          "coted",
          "toyed",
          "about",
        ],
        [
          "caged",
          "aired",
          "aurei",
        ],
        [
          "mount",
          "about",
          "about",
        ],
      ],
    ],
    [
      [
        [
          "yente",
          "blind",
          "topic",
        ],
        [
          "thale",
          "count",
          "about",
        ],
        [
          "dynel",
          "about",
          "about",
        ],
      ],
      [
        [
          "roted",
          "tynde",
          "petri",
        ],
        [
          "lythe",
          "deair",
          "about",
        ],
        [
          "blunt",
          "about",
          "about",
        ],
      ],
      [
        [
          "kynde",
          "dolce",
          "fermi",
        ],
        [
          "empty",
          "feria",
          "about",
        ],
        [
          "lindy",
          "about",
          "terai",
        ],
      ],
    ],
  ],
  [
    [
      [
        [
          "loony",
          "lints",
          "youth",
        ],
        [
          "taluk",
          "lakin",
          "costs",
        ],
        [
          "manul",
          "dimps",
          "assai",
        ],
      ],
      [
        [
          "prost",
          "brits",
          "rishi",
        ],
        [
          "bract",
          "pairs",
          "about",
        ],
        [
          "ragas",
          "brava",
          "about",
        ],
      ],
      [
        [
          "bundt",
          "klong",
          "cursi",
        ],
        [
          "plonk",
          "lapin",
          "tarsi",
        ],
        [
          "mount",
          "liras",
          "about",
        ],
      ],
    ],
    [
      [
        [
          "losen",
          "tined",
          "nisei",
        ],
        [
          "malts",
          "maise",
          "about",
        ],
        [
          "poems",
          "ideas",
          "about",
        ],
      ],
      [
        [
          "trees",
          "times",
          "about",
        ],
        [
          "talks",
          "raise",
          "about",
        ],
        [
          "hunks",
          "about",
          "about",
        ],
      ],
      [
        [
          "model",
          "chief",
          "about",
        ],
        [
          "rated",
          "about",
          "about",
        ],
        [
          "eyras",
          "about",
          "about",
        ],
      ],
    ],
    [
      [
        [
          "meted",
          "blind",
          "cesti",
        ],
        [
          "lunts",
          "aegis",
          "about",
        ],
        [
          "might",
          "about",
          "about",
        ],
      ],
      [
        [
          "reset",
          "heirs",
          "about",
        ],
        [
          "right",
          "reais",
          "about",
        ],
        [
          "water",
          "about",
          "about",
        ],
      ],
      [
        [
          "moten",
          "meris",
          "about",
        ],
        [
          "aeros",
          "about",
          "about",
        ],
        [
          "teras",
          "about",
          "about",
        ],
      ],
    ],
  ],
  [
    [
      [
        [
          "tools",
          "knits",
          "gulch",
        ],
        [
          "plans",
          "lapis",
          "sampi",
        ],
        [
          "mould",
          "kinds",
          "satai",
        ],
      ],
      [
        [
          "thump",
          "khats",
          "about",
        ],
        [
          "chant",
          "stair",
          "about",
        ],
        [
          "flong",
          "items",
          "about",
        ],
      ],
      [
        [
          "typos",
          "patch",
          "about",
        ],
        [
          "douts",
          "sarin",
          "about",
        ],
        [
          "topic",
          "about",
          "about",
        ],
      ],
    ],
    [
      [
        [
          "potes",
          "tilde",
          "solei",
        ],
        [
          "halts",
          "saine",
          "about",
        ],
        [
          "knelt",
          "about",
          "about",
        ],
      ],
      [
        [
          "opepe",
          "liver",
          "about",
        ],
        [
          "brawn",
          "about",
          "about",
        ],
        [
          "thump",
          "about",
          "about",
        ],
      ],
      [
        [
          "would",
          "needs",
          "about",
        ],
        [
          "sarge",
          "about",
          "about",
        ],
        [
          "scrae",
          "about",
          "about",
        ],
      ],
    ],
    [
      [
        [
          "dotes",
          "seise",
          "right",
        ],
        [
          "seals",
          "sepia",
          "about",
        ],
        [
          "month",
          "about",
          "about",
        ],
      ],
      [
        [
          "fixed",
          "seirs",
          "sehri",
        ],
        [
          "sears",
          "about",
          "about",
        ],
        [
          "segar",
          "about",
          "about",
        ],
      ],
      [
        [
          "moves",
          "found",
          "about",
        ],
        [
          "serra",
          "about",
          "about",
        ],
        [
          "seral",
          "about",
          "serai",
        ],
      ],
    ],
  ],
];
