extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

// To keep guess times under 2 seconds, the first guess (after the hard-coded
// guess "serai") must be precomputed.
#[wasm_bindgen]
pub fn first_guess(
  hint1: usize,
  hint2: usize,
  hint3: usize,
  hint4: usize,
  hint5: usize,
) -> Option<String> {
  CACHE[hint1][hint2][hint3][hint4][hint5].map(|word| word.to_owned())
}

const CACHE: [[[[[Option<&'static str>; 3]; 3]; 3]; 3]; 3] = [
  [
    [
      [
        [
          Some("phony."),
          Some("linty."),
          Some("mogul*"),
        ],
        [
          Some("nyala."),
          Some("mania."),
          Some("adapt*"),
        ],
        [
          Some("talon*"),
          Some("nidal."),
          Some("hotel*"),
        ],
      ],
      [
        [
          Some("choon*"),
          Some("clint*"),
          Some("kombu*"),
        ],
        [
          Some("orant."),
          Some("lakin*"),
          Some("guard*"),
        ],
        [
          Some("talon*"),
          Some("milty*"),
          Some("braai."),
        ],
      ],
      [
        [
          Some("culty*"),
          Some("monty*"),
          Some("ultra*"),
        ],
        [
          Some("comby*"),
          Some("mania*"),
          Some("capri*"),
        ],
        [
          Some("alamo*"),
          Some("diram."),
          Some("korai."),
        ],
      ],
    ],
    [
      [
        [
          Some("dolce."),
          Some("nitid*"),
          Some("flock*"),
        ],
        [
          Some("lawed."),
          Some("maile."),
          Some("naevi!"),
        ],
        [
          Some("pleon*"),
          Some("email*"),
          None,
        ],
      ],
      [
        [
          Some("coted*"),
          Some("lined*"),
          Some("uteri!"),
        ],
        [
          Some("gator*"),
          Some("alarm*"),
          Some("uraei!"),
        ],
        [
          Some("arked*"),
          Some("rimae!"),
          None,
        ],
      ],
      [
        [
          Some("coted*"),
          Some("toyed*"),
          None,
        ],
        [
          Some("caged*"),
          Some("aired."),
          Some("aurei!"),
        ],
        [
          Some("mount*"),
          None,
          None,
        ],
      ],
    ],
    [
      [
        [
          Some("yente."),
          Some("blind*"),
          Some("topic*"),
        ],
        [
          Some("thale*"),
          Some("count*"),
          None,
        ],
        [
          Some("dynel*"),
          None,
          None,
        ],
      ],
      [
        [
          Some("roted*"),
          Some("tynde*"),
          Some("petri."),
        ],
        [
          Some("lythe*"),
          Some("deair."),
          None,
        ],
        [
          Some("blunt*"),
          None,
          None,
        ],
      ],
      [
        [
          Some("kynde*"),
          Some("dolce*"),
          Some("fermi."),
        ],
        [
          Some("empty*"),
          Some("feria."),
          None,
        ],
        [
          Some("lindy*"),
          None,
          Some("terai."),
        ],
      ],
    ],
  ],
  [
    [
      [
        [
          Some("loony*"),
          Some("lints."),
          Some("youth*"),
        ],
        [
          Some("taluk*"),
          Some("lakin*"),
          Some("costs*"),
        ],
        [
          Some("manul*"),
          Some("dimps*"),
          Some("assai."),
        ],
      ],
      [
        [
          Some("prost."),
          Some("brits."),
          Some("rishi."),
        ],
        [
          Some("bract*"),
          Some("pairs."),
          None,
        ],
        [
          Some("ragas."),
          Some("brava*"),
          None,
        ],
      ],
      [
        [
          Some("bundt*"),
          Some("klong*"),
          Some("cursi."),
        ],
        [
          Some("plonk*"),
          Some("lapin*"),
          Some("tarsi!"),
        ],
        [
          Some("mount*"),
          Some("liras!"),
          None,
        ],
      ],
    ],
    [
      [
        [
          Some("losen."),
          Some("tined*"),
          Some("nisei."),
        ],
        [
          Some("malts*"),
          Some("maise."),
          None,
        ],
        [
          Some("poems*"),
          Some("ideas."),
          None,
        ],
      ],
      [
        [
          Some("trees."),
          Some("times*"),
          None,
        ],
        [
          Some("talks*"),
          Some("raise."),
          None,
        ],
        [
          Some("hunks*"),
          None,
          None,
        ],
      ],
      [
        [
          Some("model*"),
          Some("chief*"),
          None,
        ],
        [
          Some("rated*"),
          None,
          None,
        ],
        [
          Some("eyras!"),
          None,
          None,
        ],
      ],
    ],
    [
      [
        [
          Some("meted*"),
          Some("blind*"),
          Some("cesti."),
        ],
        [
          Some("lunts*"),
          Some("aegis!"),
          None,
        ],
        [
          Some("might*"),
          None,
          None,
        ],
      ],
      [
        [
          Some("reset."),
          Some("heirs."),
          None,
        ],
        [
          Some("right*"),
          Some("reais."),
          None,
        ],
        [
          Some("water*"),
          None,
          None,
        ],
      ],
      [
        [
          Some("moten*"),
          Some("meris."),
          None,
        ],
        [
          Some("aeros!"),
          None,
          None,
        ],
        [
          Some("teras!"),
          None,
          None,
        ],
      ],
    ],
  ],
  [
    [
      [
        [
          Some("tools*"),
          Some("knits*"),
          Some("gulch*"),
        ],
        [
          Some("plans*"),
          Some("lapis*"),
          Some("sampi."),
        ],
        [
          Some("mould*"),
          Some("kinds*"),
          Some("satai."),
        ],
      ],
      [
        [
          Some("thump*"),
          Some("khats*"),
          None,
        ],
        [
          Some("chant*"),
          Some("stair."),
          None,
        ],
        [
          Some("flong*"),
          Some("items*"),
          None,
        ],
      ],
      [
        [
          Some("typos*"),
          Some("patch*"),
          None,
        ],
        [
          Some("douts*"),
          Some("sarin."),
          None,
        ],
        [
          Some("topic*"),
          None,
          None,
        ],
      ],
    ],
    [
      [
        [
          Some("potes*"),
          Some("tilde*"),
          Some("solei!"),
        ],
        [
          Some("halts*"),
          Some("saine."),
          None,
        ],
        [
          Some("knelt*"),
          None,
          None,
        ],
      ],
      [
        [
          Some("opepe*"),
          Some("liver*"),
          None,
        ],
        [
          Some("brawn*"),
          None,
          None,
        ],
        [
          Some("thump*"),
          None,
          None,
        ],
      ],
      [
        [
          Some("would*"),
          Some("needs*"),
          None,
        ],
        [
          Some("sarge."),
          None,
          None,
        ],
        [
          Some("scrae."),
          None,
          None,
        ],
      ],
    ],
    [
      [
        [
          Some("dotes*"),
          Some("seise."),
          Some("right*"),
        ],
        [
          Some("seals."),
          Some("sepia."),
          None,
        ],
        [
          Some("month*"),
          None,
          None,
        ],
      ],
      [
        [
          Some("fixed*"),
          Some("seirs!"),
          Some("sehri!"),
        ],
        [
          Some("sears."),
          None,
          None,
        ],
        [
          Some("segar."),
          None,
          None,
        ],
      ],
      [
        [
          Some("moves*"),
          Some("found*"),
          None,
        ],
        [
          Some("serra!"),
          None,
          None,
        ],
        [
          Some("seral."),
          None,
          Some("serai!"),
        ],
      ],
    ],
  ],
]
;
